version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: erp-mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - erp-network
    environment:
      - MONGO_INITDB_DATABASE=idurar-erp-crm
    ports:
      - "27017:27017"

  backend:
    image: naga2112/erp-crm-backend-jenkins:latest1
    container_name: erp-backend
    restart: always
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=production
      - DATABASE=mongodb://mongo:27017/idurar-erp-crm
      - PORT=8888
      - JWT_SECRET=your_super_secret_key_change_this
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - mongo
    networks:
      - erp-network

  frontend:
    image: naga2112/erp-crm-frontend-jenkins:latest2
    container_name: erp-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8888/api
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - backend
    networks:
      - erp-network

volumes:
  mongodb_data:

networks:
  erp-network:
    driver: bridge